<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Adapters\**" />
    <Compile Remove="Configs\**" />
    <Compile Remove="Persistence\**" />
    <EmbeddedResource Remove="Adapters\**" />
    <EmbeddedResource Remove="Configs\**" />
    <EmbeddedResource Remove="Persistence\**" />
    <None Remove="Adapters\**" />
    <None Remove="Configs\**" />
    <None Remove="Persistence\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Q.Initializer\Q.Initializer.csproj" />
    <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
  </ItemGroup>

</Project>
