<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.0" />
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Q.Initializer\Q.Initializer.csproj" />
    <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
    <ProjectReference Include="..\SearchService.Infrastructure\SearchService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
